[build]
  command = "pip install -r requirements-prod.txt"
  functions = "fitnova/netlify/functions"

[functions]
  python_bundler = "nft"
  external_node_modules = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
